/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Cliente;
import Modelo.Consultorio;
import Modelo.Masajista;
import Persistencia.TratamientoData;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;

//Dios los bendiga a todos, les traiga paz y amor a sus corazones y nunca los abandone, Amén.

/**
 *
 * @author matute
 */
public class jfSpaRelax extends javax.swing.JFrame {
    public static ArrayList<Cliente> listaClientes = new ArrayList<>();
    public static ArrayList<Consultorio> listaConsultorios = new ArrayList<>();
    public static ArrayList<Masajista> listaMasajista=new ArrayList<>();
    public static TratamientoData tratamientoData;
    /**
     * Creates new form SpaRelax
     */
    public jfSpaRelax() {
        initComponents();
        jdpEscritorio = new DesktopConFondo("/img/spa.jpeg");
        setContentPane(jdpEscritorio);
        tratamientoData = new TratamientoData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpEscritorio = new javax.swing.JDesktopPane();
        jmbBarraMenu = new javax.swing.JMenuBar();
        jmClientes = new javax.swing.JMenu();
        jmiGestionClientes = new javax.swing.JMenuItem();
        jmInstalaciones = new javax.swing.JMenu();
        jmiGestionInstalaciones = new javax.swing.JMenuItem();
        jmConsultorios = new javax.swing.JMenu();
        jmGestionConsultorios = new javax.swing.JMenuItem();
        jmMasajistas = new javax.swing.JMenu();
        jmiGestionMasajistas = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmTratamientos = new javax.swing.JMenu();
        jmiGestionTratamientos = new javax.swing.JMenuItem();
        jmSesiones = new javax.swing.JMenu();
        jmiSesiones = new javax.swing.JMenuItem();
        jmDiaSpa = new javax.swing.JMenu();
        jmiDiaSpa = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpEscritorioLayout = new javax.swing.GroupLayout(jdpEscritorio);
        jdpEscritorio.setLayout(jdpEscritorioLayout);
        jdpEscritorioLayout.setHorizontalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        jdpEscritorioLayout.setVerticalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );

        jmClientes.setText("Clientes");

        jmiGestionClientes.setText("Gestion de Clientes");
        jmiGestionClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionClientesActionPerformed(evt);
            }
        });
        jmClientes.add(jmiGestionClientes);

        jmbBarraMenu.add(jmClientes);

        jmInstalaciones.setText("Instalaciones");

        jmiGestionInstalaciones.setText("Gestion de Instalaciones");
        jmiGestionInstalaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionInstalacionesActionPerformed(evt);
            }
        });
        jmInstalaciones.add(jmiGestionInstalaciones);

        jmbBarraMenu.add(jmInstalaciones);

        jmConsultorios.setText("Consultorios");

        jmGestionConsultorios.setText("Gestion de Consultorios");
        jmGestionConsultorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmGestionConsultoriosActionPerformed(evt);
            }
        });
        jmConsultorios.add(jmGestionConsultorios);

        jmbBarraMenu.add(jmConsultorios);

        jmMasajistas.setText("Masajistas");

        jmiGestionMasajistas.setText("Gestion de Masajistas");
        jmiGestionMasajistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionMasajistasActionPerformed(evt);
            }
        });
        jmMasajistas.add(jmiGestionMasajistas);

        jMenuItem1.setText("Turnos de los Masajistas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmMasajistas.add(jMenuItem1);

        jmbBarraMenu.add(jmMasajistas);

        jmTratamientos.setText("Tratamientos");

        jmiGestionTratamientos.setText("Gestion de Tratamientos");
        jmiGestionTratamientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionTratamientosActionPerformed(evt);
            }
        });
        jmTratamientos.add(jmiGestionTratamientos);

        jmbBarraMenu.add(jmTratamientos);

        jmSesiones.setText("Sesiones");

        jmiSesiones.setText("Gestion de Sesiones");
        jmSesiones.add(jmiSesiones);

        jmbBarraMenu.add(jmSesiones);

        jmDiaSpa.setText("Dia de Spa");
        jmDiaSpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDiaSpaActionPerformed(evt);
            }
        });

        jmiDiaSpa.setText("Gestion de Dias de Spa");
        jmiDiaSpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDiaSpaActionPerformed(evt);
            }
        });
        jmDiaSpa.add(jmiDiaSpa);

        jmbBarraMenu.add(jmDiaSpa);

        setJMenuBar(jmbBarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiGestionClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionClientesActionPerformed
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        jifGestionClientes g = new jifGestionClientes();
        g.setVisible(true);
        jdpEscritorio.add(g);
        g.toFront();
    }//GEN-LAST:event_jmiGestionClientesActionPerformed

    private void jmiGestionInstalacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionInstalacionesActionPerformed
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        jifGestionInstalacion g = new jifGestionInstalacion();
        g.setVisible(true);
        jdpEscritorio.add(g);
        g.toFront();
    }//GEN-LAST:event_jmiGestionInstalacionesActionPerformed

    private void jmGestionConsultoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmGestionConsultoriosActionPerformed
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        jifGestionConsultorios g = new jifGestionConsultorios();
        g.setVisible(true);
        jdpEscritorio.add(g);
        g.toFront();
    }//GEN-LAST:event_jmGestionConsultoriosActionPerformed

    private void jmiGestionMasajistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionMasajistasActionPerformed
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        jifGestionMasajista g = new jifGestionMasajista();
        g.setVisible(true);
        jdpEscritorio.add(g);
        g.toFront();
    }//GEN-LAST:event_jmiGestionMasajistasActionPerformed

    private void jmiGestionTratamientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionTratamientosActionPerformed
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        jifGestionTratamientos gT = new jifGestionTratamientos();
        jdpEscritorio.add(gT);
        gT.setVisible(true);
        gT.moveToFront();
    }//GEN-LAST:event_jmiGestionTratamientosActionPerformed

    private void jmDiaSpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDiaSpaActionPerformed
       
    }//GEN-LAST:event_jmDiaSpaActionPerformed

    private void jmiDiaSpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDiaSpaActionPerformed
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        jifGestionDiaDeSpa ds = new jifGestionDiaDeSpa();
        jdpEscritorio.add(ds);
        ds.setVisible(true);
        ds.moveToFront();
    }//GEN-LAST:event_jmiDiaSpaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        jifMasajistasLibres ds = new jifMasajistasLibres();
        jdpEscritorio.add(ds);
        ds.setVisible(true);
        ds.moveToFront();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfSpaRelax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfSpaRelax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfSpaRelax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfSpaRelax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfSpaRelax().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JDesktopPane jdpEscritorio;
    private javax.swing.JMenu jmClientes;
    private javax.swing.JMenu jmConsultorios;
    private javax.swing.JMenu jmDiaSpa;
    private javax.swing.JMenuItem jmGestionConsultorios;
    private javax.swing.JMenu jmInstalaciones;
    private javax.swing.JMenu jmMasajistas;
    private javax.swing.JMenu jmSesiones;
    private javax.swing.JMenu jmTratamientos;
    private javax.swing.JMenuBar jmbBarraMenu;
    private javax.swing.JMenuItem jmiDiaSpa;
    private javax.swing.JMenuItem jmiGestionClientes;
    private javax.swing.JMenuItem jmiGestionInstalaciones;
    private javax.swing.JMenuItem jmiGestionMasajistas;
    private javax.swing.JMenuItem jmiGestionTratamientos;
    private javax.swing.JMenuItem jmiSesiones;
    // End of variables declaration//GEN-END:variables
class DesktopConFondo extends JDesktopPane {
        private Image imagen;
        public DesktopConFondo(String rutaImagen) {
            java.net.URL imgURL = getClass().getResource(rutaImagen);
        if (imgURL != null) {
            this.imagen = new ImageIcon(imgURL).getImage();
        } else {
            System.err.println("No se encontró la imagen: " + rutaImagen);
            }
        }
        
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            if (imagen != null) {
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            }
        }
    }
}
