package Vista;

import Modelo.Cliente;
import Persistencia.ClienteData;
import static Vista.jfSpaRelax.listaClientes;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class jifGestionClientes extends javax.swing.JInternalFrame {

    ClienteData cd;
    private String estadoOperacion = "ninguno";
    private int codClienteSeleccionado = -1;
    private boolean tablaVisible = false;

    private final DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }

    };

    /**
     * Creates new form jifGestionClientes
     */
    public jifGestionClientes() {
        initComponents();
        this.cd = new ClienteData();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfDNI = new javax.swing.JTextField();
        jtfNombreCompleto = new javax.swing.JTextField();
        jtfTelefono = new javax.swing.JTextField();
        jtfEdad = new javax.swing.JTextField();
        jtfAfecciones = new javax.swing.JTextField();
        jbNuevo = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jbBorrar = new javax.swing.JButton();
        jbAlta = new javax.swing.JButton();
        jbBaja = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTablaClientes = new javax.swing.JTable();
        jbMostrarClientes = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Nimbus Sans", 1, 30)); // NOI18N
        jLabel1.setText("Gestión de Clientes");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingreso de datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel2.setText("Nombre Completo:");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel3.setText("DNI:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel4.setText("Telefono:");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel5.setText("Edad:");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel6.setText("Afecciones:");

        jtfDNI.setEnabled(false);

        jtfNombreCompleto.setEnabled(false);

        jtfTelefono.setEnabled(false);

        jtfEdad.setEnabled(false);

        jtfAfecciones.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfDNI)
                    .addComponent(jtfNombreCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(jtfTelefono)
                    .addComponent(jtfEdad)
                    .addComponent(jtfAfecciones))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfAfecciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jbNuevo.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbActualizar.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jbActualizar.setText("Actualizar");
        jbActualizar.setEnabled(false);
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jbBorrar.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jbBorrar.setText("Borrar");
        jbBorrar.setEnabled(false);
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        jbAlta.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jbAlta.setText("Alta");
        jbAlta.setEnabled(false);
        jbAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaActionPerformed(evt);
            }
        });

        jbBaja.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jbBaja.setText("Baja");
        jbBaja.setEnabled(false);
        jbBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajaActionPerformed(evt);
            }
        });

        jbGuardar.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jbGuardar.setText("Guardar");
        jbGuardar.setEnabled(false);
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jtTablaClientes.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jtTablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtTablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTablaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtTablaClientes);

        jbMostrarClientes.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jbMostrarClientes.setText("Mostrar Clientes");
        jbMostrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMostrarClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jbMostrarClientes))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbActualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbAlta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbBaja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(jbActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(jbBorrar)
                        .addGap(18, 18, 18)
                        .addComponent(jbAlta)
                        .addGap(18, 18, 18)
                        .addComponent(jbBaja)
                        .addGap(18, 18, 18)
                        .addComponent(jbGuardar))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbMostrarClientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarTabla() {
        listaClientes = cd.obtenerClientes();
        modelo.setRowCount(0);

        for (Cliente c : listaClientes) {
            Object[] fila = {
                c.getIdCliente(),
                c.getDni(),
                c.getNombreCompleto(),
                c.getEdad(),
                c.getTelefono(),
                (c.isEstado() ? "Activo" : "Inactivo")
            };
            modelo.addRow(fila);
        }
    }

    private Cliente buscarClientePorCodigo(int codigoCliente) {
        listaClientes = cd.obtenerClientes();

        for (Cliente c : listaClientes) {
            if (c.getIdCliente() == codigoCliente) {
                return c;
            }
        }
        return null;
    }

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        estadoOperacion = "Nuevo";

        jtfDNI.setText("");
        jtfNombreCompleto.setText("");
        jtfTelefono.setText("");
        jtfEdad.setText("");
        jtfAfecciones.setText("");

        jtfDNI.setEnabled(true);
        jtfNombreCompleto.setEnabled(true);
        jtfTelefono.setEnabled(true);
        jtfEdad.setEnabled(true);
        jtfAfecciones.setEnabled(true);

        jbNuevo.setEnabled(false);
        jbGuardar.setEnabled(true);
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbMostrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMostrarClientesActionPerformed
        if (tablaVisible == false) {
            cargarTabla();
            tablaVisible = true;
            jbMostrarClientes.setText("Actualiar Tabla");
        } else {
            cargarTabla();
        }
    }//GEN-LAST:event_jbMostrarClientesActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        int filaSeleccionada = jtTablaClientes.getSelectedRow();

        if (filaSeleccionada != -1) {
            Object valorId = jtTablaClientes.getValueAt(filaSeleccionada, 0);

            int codigoCliente = Integer.parseInt(valorId.toString());
            this.codClienteSeleccionado = codigoCliente;
            Cliente clienteSeleccionado = buscarClientePorCodigo(codigoCliente);

            if (clienteSeleccionado != null) {
                estadoOperacion = "Actualizar";
                
                jtfDNI.setText(String.valueOf(clienteSeleccionado.getDni()));
                jtfNombreCompleto.setText(clienteSeleccionado.getNombreCompleto());
                jtfTelefono.setText(String.valueOf(clienteSeleccionado.getTelefono()));
                jtfEdad.setText(String.valueOf(clienteSeleccionado.getEdad()));
                jtfAfecciones.setText(clienteSeleccionado.getAfecciones());

                jtfDNI.setEnabled(true);
                jtfNombreCompleto.setEnabled(true);
                jtfTelefono.setEnabled(true);
                jtfEdad.setEnabled(true);
                jtfAfecciones.setEnabled(true);

                jbGuardar.setEnabled(true);
                jbNuevo.setEnabled(false);
                jbBorrar.setEnabled(false);
                jbActualizar.setEnabled(false);
                jbAlta.setEnabled(false);
                jbBaja.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jtTablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTablaClientesMouseClicked
        int filaSeleccionada = jtTablaClientes.getSelectedRow();
        if (filaSeleccionada != -1) {
            jbActualizar.setEnabled(true);
            jbBorrar.setEnabled(true);
            jbAlta.setEnabled(true);
            jbBaja.setEnabled(true);
        }
    }//GEN-LAST:event_jtTablaClientesMouseClicked

    private void jbAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaActionPerformed
        if (jtTablaClientes.getSelectedRow() != -1) {
            int id = 0;
            Integer idCliente = (Integer) modelo.getValueAt(jtTablaClientes.getSelectedRow(), id);
            for (Cliente c : cd.obtenerClientes()) {
                if (idCliente == c.getIdCliente() && c.isEstado() == true) {
                    JOptionPane.showMessageDialog(this, "El cliente ya se encuentra activo.");
                    return;
                } else if (idCliente == c.getIdCliente() && c.isEstado() == false) {
                    cd.altaCliente(idCliente);
                    JOptionPane.showMessageDialog(this, "Cliente dado de alta exitosamente.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una fila antes de continuar.");
        }
        cargarTabla();
    }//GEN-LAST:event_jbAltaActionPerformed

    private void jbBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajaActionPerformed
        if (jtTablaClientes.getSelectedRow() != -1) {
            int id = 0;
            Integer idCliente = (Integer) modelo.getValueAt(jtTablaClientes.getSelectedRow(), id);
            for (Cliente c : cd.obtenerClientes()) {
                if (idCliente == c.getIdCliente() && c.isEstado() == false) {
                    JOptionPane.showMessageDialog(this, "El cliente ya se encuentra inactivo.");
                    return;
                } else if (idCliente == c.getIdCliente() && c.isEstado() == true) {
                    cd.bajaCliente(idCliente);
                    JOptionPane.showMessageDialog(this, "Cliente dado de baja exitosamente.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una fila antes de continuar.");
        }
        cargarTabla();
    }//GEN-LAST:event_jbBajaActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        jbNuevo.setEnabled(false);
        jbActualizar.setEnabled(false);
        jbAlta.setEnabled(false);
        jbBaja.setEnabled(false);
        
        int filaSeleccionada = jtTablaClientes.getSelectedRow();

        if (filaSeleccionada != -1) {
            int opcion = JOptionPane.showConfirmDialog(this, "Estas seguro de que queres borrar los datos del Cliente?",
                    "Confirmar Borrado", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                Object valorId = jtTablaClientes.getValueAt(filaSeleccionada, 0);
                int codigoCliente = Integer.parseInt(valorId.toString());
                Cliente clienteSeleccionado = buscarClientePorCodigo(codigoCliente);

                if (clienteSeleccionado != null) {
                    cd.borrarCliente(clienteSeleccionado.getIdCliente());
                    JOptionPane.showMessageDialog(this, "Cliente borrado con exito.");

                    cargarTabla();
                    jtfDNI.setText("");
                    jtfNombreCompleto.setText("");
                    jtfTelefono.setText("");
                    jtfEdad.setText("");
                    jtfAfecciones.setText("");
                    jbBorrar.setEnabled(false);
                    jbNuevo.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontro el Cliente.", "Error de Busqueda",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se Encontro la Fila Seleccionada.", "Error de Busqueda",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        String regex = "^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$";
        boolean clienteExiste = false;
        
        try {
            if (!jtfNombreCompleto.getText().matches(regex) || jtfNombreCompleto.getText().isEmpty() || !jtfAfecciones.getText().matches(regex) || jtfAfecciones.getText().isEmpty() || jtfDNI.getText().matches(regex) || jtfDNI.getText().isEmpty() || jtfTelefono.getText().matches(regex) || jtfTelefono.getText().isEmpty() || jtfEdad.getText().matches(regex) || jtfEdad.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Uno o muchos campos contienen carácteres incorrectos.", "Error de formato", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "En dni, edad y telefono solo debe ingresar numeros.", "Error de formato numerico", JOptionPane.ERROR_MESSAGE);
        }

        listaClientes = cd.obtenerClientes();
        int dniIngresado = Integer.parseInt(jtfDNI.getText());

        if (estadoOperacion.equalsIgnoreCase("Nuevo")) {

            for (Cliente cliente : listaClientes) {
                if (cliente.getDni() == dniIngresado) {
                    clienteExiste = true;
                    break;
                }
            }

            if (clienteExiste) {
                JOptionPane.showMessageDialog(this, "Ya existe un Cliente con el DNI ingresado.", "Error. Cliente Existente", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Cliente nuevoCliente = new Cliente(Integer.parseInt(jtfDNI.getText()), jtfNombreCompleto.getText(), Long.parseLong(jtfTelefono.getText()), Integer.parseInt(jtfEdad.getText()), jtfAfecciones.getText());

            cd.insertarCliente(nuevoCliente);
            JOptionPane.showMessageDialog(this, "¡Cliente agregado con exito!");

            estadoOperacion = "Ninguno";

        } else if (estadoOperacion.equalsIgnoreCase("Actualizar")) {
            int codClienteActualizar = this.codClienteSeleccionado;
            Cliente clienteActualizar = buscarClientePorCodigo(codClienteActualizar);

            if (clienteActualizar != null) {
                cd.actualizarCliente(
                    codClienteActualizar, 
                    Integer.parseInt(jtfDNI.getText()), 
                    jtfNombreCompleto.getText(), 
                    Long.parseLong(jtfTelefono.getText()), 
                    Integer.parseInt(jtfEdad.getText()), 
                    jtfAfecciones.getText()
                );
                    JOptionPane.showMessageDialog(this, "Cliente actualizado con Exito!");
                    this.codClienteSeleccionado = -1;
            } else {
                JOptionPane.showMessageDialog(this, "No se encontro el Cliente.", "Error de Busqueda", JOptionPane.ERROR_MESSAGE);
            }
            estadoOperacion = "Ninguno";
        }

        if (jbMostrarClientes.getText().equalsIgnoreCase("Mostrar Clientes")) {
            cargarTabla();
            jbMostrarClientes.setText("Ocultar Clientes");
        } else if (jbMostrarClientes.getText().equalsIgnoreCase("Ocultar Clientes")) {
            cargarTabla();
        }

        jtfDNI.setText("");
        jtfNombreCompleto.setText("");
        jtfTelefono.setText("");
        jtfEdad.setText("");
        jtfAfecciones.setText("");

        jbGuardar.setEnabled(false);
        jbNuevo.setEnabled(true);
        jbAlta.setEnabled(false);
        jbBaja.setEnabled(false);

        jtfDNI.setEnabled(false);
        jtfNombreCompleto.setEnabled(false);
        jtfTelefono.setEnabled(false);
        jtfEdad.setEnabled(false);
        jtfAfecciones.setEnabled(false);
    }//GEN-LAST:event_jbGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbAlta;
    private javax.swing.JButton jbBaja;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbMostrarClientes;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JTable jtTablaClientes;
    private javax.swing.JTextField jtfAfecciones;
    private javax.swing.JTextField jtfDNI;
    private javax.swing.JTextField jtfEdad;
    private javax.swing.JTextField jtfNombreCompleto;
    private javax.swing.JTextField jtfTelefono;
    // End of variables declaration//GEN-END:variables
private void armarCabecera() {
        modelo.addColumn("Codigo");
        modelo.addColumn("DNI");
        modelo.addColumn("Nombre Completo");
        modelo.addColumn("Edad");
        modelo.addColumn("Telefono");
        modelo.addColumn("Estado");

        jtTablaClientes.setModel(modelo);
    }
}
