package Vista;

import Persistencia.TratamientoData;
import Persistencia.Conexion;
import Modelo.Tratamiento;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
/**
 *
 * @author dannita
 */
public class jifGestionTratamientos extends javax.swing.JInternalFrame {
    private TratamientoData tratamientoData;
    private boolean aux = false; // Me ayuda a manejar el flujo de mi codigo en los eventos de los botones.
    private String regex = "^[a-zA-ZáéíóúÁÉÍÓÚñÑ,\\s]+$"; // Expresion regular para letras.
    private String regex2 = "^[\\d.]+$"; // Expresion regular para digitos numericos.
    Connection conexion = Conexion.establecerConexion(); // Guardo el resultado. Si null, ejecuto flujo de linea 35, no permitiendole al usuario continuar hasta que establezca la conexion a la bd.
    private DefaultTableModel modeloTabla = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    /**
     * Creates new form jifGestionTratamientos
     */
    public jifGestionTratamientos() {
        initComponents();
        this.tratamientoData = new TratamientoData();
        if (this.conexion == null) {
            JOptionPane.showMessageDialog(null, "No existe una conexion a una base de datos.\nEstablezcala antes de continuar.");
            limpiarCampos();
            deshabilitarBotones();
            deshabilitarCampos();
            jTablaTratamientos.setEnabled(false);
            jButtonActualizarLista.setEnabled(false);
        }
        cargarId(); // Carga el Combo Box de los ID de los tratamientos.
        columns(); // Setea columnas de la tabla.
        rows(); // Setea filas de la tabla. Excepciones controladas en 'TratamientoData'.
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxIds = new javax.swing.JComboBox<>();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldDetalle = new javax.swing.JTextField();
        jTextFieldDuracion = new javax.swing.JTextField();
        jTextFieldCosto = new javax.swing.JTextField();
        jTextFieldProductos = new javax.swing.JTextField();
        jButtonActualizarTratamiento = new javax.swing.JButton();
        jButtonBorrarTratamiento = new javax.swing.JButton();
        jButtonCargarTratamiento = new javax.swing.JButton();
        jButtonTratamientoOn = new javax.swing.JButton();
        jButtonTratamientoOff = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonActualizarLista = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaTratamientos = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jRadioButtonFacial = new javax.swing.JRadioButton();
        jRadioButtonCorporal = new javax.swing.JRadioButton();
        jRadioButtonRelajacion = new javax.swing.JRadioButton();
        jRadioButtonEstetico = new javax.swing.JRadioButton();
        jRadioButtonTodos = new javax.swing.JRadioButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Nimbus Sans", 1, 30)); // NOI18N
        jLabel1.setText("Gestión de tratamientos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13)), "Ingreso de datos:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel2.setText("Id tratamiento:");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel3.setText("Tipo:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel4.setText("Detalle:");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel5.setText("Costo:");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel6.setText("Duración por hora:");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel7.setText("Productos:");

        jComboBoxIds.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jComboBoxIds.setBorder(null);
        jComboBoxIds.setEnabled(false);

        jTextFieldNombre.setEnabled(false);

        jTextFieldDetalle.setEnabled(false);

        jTextFieldDuracion.setEnabled(false);

        jTextFieldCosto.setEnabled(false);

        jTextFieldProductos.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel7)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jComboBoxIds, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                        .addComponent(jTextFieldNombre)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxIds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jButtonActualizarTratamiento.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jButtonActualizarTratamiento.setText("Actualizar tratamiento");
        jButtonActualizarTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarTratamientoActionPerformed(evt);
            }
        });

        jButtonBorrarTratamiento.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jButtonBorrarTratamiento.setText("Borrar tratamiento");
        jButtonBorrarTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarTratamientoActionPerformed(evt);
            }
        });

        jButtonCargarTratamiento.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jButtonCargarTratamiento.setText("Cargar tratamiento");
        jButtonCargarTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarTratamientoActionPerformed(evt);
            }
        });

        jButtonTratamientoOn.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jButtonTratamientoOn.setText("Habilitar tratamiento");
        jButtonTratamientoOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTratamientoOnActionPerformed(evt);
            }
        });

        jButtonTratamientoOff.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jButtonTratamientoOff.setText("Deshabilitar tratamiento");
        jButtonTratamientoOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTratamientoOffActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonActualizarLista.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jButtonActualizarLista.setText("Actualizar lista");
        jButtonActualizarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarListaActionPerformed(evt);
            }
        });

        jTablaTratamientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablaTratamientos);

        jLabel9.setFont(new java.awt.Font("Nimbus Sans", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Tipos de tratamientos ");

        buttonGroup1.add(jRadioButtonFacial);
        jRadioButtonFacial.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jRadioButtonFacial.setText("Facial");
        jRadioButtonFacial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonFacialMouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButtonCorporal);
        jRadioButtonCorporal.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jRadioButtonCorporal.setText("Corporal");
        jRadioButtonCorporal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonCorporalMouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButtonRelajacion);
        jRadioButtonRelajacion.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jRadioButtonRelajacion.setText("Relajación");
        jRadioButtonRelajacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonRelajacionMouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButtonEstetico);
        jRadioButtonEstetico.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jRadioButtonEstetico.setText("Estético");
        jRadioButtonEstetico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonEsteticoMouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButtonTodos);
        jRadioButtonTodos.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jRadioButtonTodos.setSelected(true);
        jRadioButtonTodos.setText("Todos");
        jRadioButtonTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonTodosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addComponent(jLabel9)))
                        .addGap(146, 146, 146))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jRadioButtonRelajacion)
                                .addComponent(jRadioButtonCorporal, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButtonFacial, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButtonEstetico, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButtonTodos, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonCargarTratamiento)
                                .addComponent(jButtonActualizarTratamiento)
                                .addComponent(jButtonCancelar)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonTratamientoOn)
                            .addGap(40, 40, 40)
                            .addComponent(jButtonTratamientoOff)
                            .addGap(45, 45, 45)
                            .addComponent(jButtonBorrarTratamiento))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(225, 225, 225)
                            .addComponent(jButtonActualizarLista))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButtonCargarTratamiento)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonActualizarTratamiento)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelar)))
                .addGap(22, 22, 22)
                .addComponent(jLabel9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jRadioButtonTodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonFacial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonCorporal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonRelajacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonEstetico)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonActualizarLista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTratamientoOn)
                    .addComponent(jButtonTratamientoOff)
                    .addComponent(jButtonBorrarTratamiento))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCargarTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarTratamientoActionPerformed
        if (aux == false) {
            habilitarCampos();
            deshabilitarBotones();
            jComboBoxIds.setEnabled(false);
            jButtonCargarTratamiento.setEnabled(true);
            jButtonCancelar.setEnabled(true);
            aux = true; 
            return;
            /* Devuelvo true y return para el siguiente flujo de codigo. Permitiendome que los JOption no
            salten al primer instante
            */
        }

        if (aux == true) {
            if (!jTextFieldNombre.getText().matches(regex) || jTextFieldNombre.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Asegurese de ingresar datos correctos en el campo de 'Nombre'.");
                return;
            } else if (!jTextFieldDetalle.getText().matches(regex) || jTextFieldDetalle.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Asegurese de ingresar datos correctos en el campo de 'Detalle'.");
                return;
            } else if (!jTextFieldProductos.getText().matches(regex) || jTextFieldProductos.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Asegurese de ingresar datos correctos en el campo de 'Productos'.");
                return;
            } else if (!jTextFieldDuracion.getText().matches(regex2) || jTextFieldDuracion.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Asegurese de ingresar datos correctos en el campo de 'Duracion'.");
                return;
            } else if (!jTextFieldCosto.getText().matches(regex2) || jTextFieldCosto.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Asegurese de ingresar datos correctos en el campo de 'Costo'.");
                return;
            }

            List<String> productos = new ArrayList<>();
            productos.add(jTextFieldProductos.getText());
            tratamientoData.agregarTratamiento(new Tratamiento(jTextFieldNombre.getText(), jTextFieldDetalle.getText(), productos, Integer.parseInt(jTextFieldDuracion.getText()), Double.parseDouble(jTextFieldCosto.getText())));
            limpiarCampos();
            deshabilitarCampos();
            habilitarBotones();
            aux = false;
        }
    }//GEN-LAST:event_jButtonCargarTratamientoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        limpiarCampos();
        deshabilitarCampos();
        habilitarBotones();
        jButtonCancelar.setEnabled(false);
        if (aux == true) {
            aux = false;
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonActualizarTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarTratamientoActionPerformed
        if (aux == false) {
            deshabilitarBotones();
            jButtonActualizarTratamiento.setEnabled(true);
            jButtonCancelar.setEnabled(true);
            JOptionPane.showMessageDialog(this, "Seleccione un tratamiento de la lista y presione 'Actualizar'.");
            aux = true;
            return;
        }
        if (aux == true) {
            if (jTablaTratamientos.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(this, "Seleccione una fila antes de continuar.");
                return;
            }
            if (jTextFieldNombre.getText().isEmpty()) {
                habilitarCampos();
                jComboBoxIds.setEnabled(false);
                Integer idTratamiento = (Integer) modeloTabla.getValueAt(jTablaTratamientos.getSelectedRow(), 0);
                for (Tratamiento tratamiento : tratamientoData.mostrarTratamientos()) {
                    if (idTratamiento == tratamiento.getIdTratamiento()) {
                        jComboBoxIds.setSelectedItem(tratamiento.getIdTratamiento());
                        jTextFieldNombre.setText(tratamiento.getNombre());
                        jTextFieldDetalle.setText(tratamiento.getDetalle());
                        jTextFieldProductos.setText(tratamiento.getProductosT());
                        jTextFieldDuracion.setText(String.valueOf(tratamiento.getDuracion()));
                        jTextFieldCosto.setText(String.valueOf(tratamiento.getCosto()));
                        return;
                    }
                }
            }
            
            
            int seleccionId = (int) jComboBoxIds.getSelectedItem();
            String productos = jTextFieldProductos.getText();
            tratamientoData.actualizarTratamiento(seleccionId, jTextFieldNombre.getText(), jTextFieldDetalle.getText(), productos, Integer.parseInt(jTextFieldDuracion.getText()), Double.parseDouble(jTextFieldCosto.getText()));
            limpiarCampos();
            deshabilitarCampos();
            habilitarBotones();
            jButtonCancelar.setEnabled(false);
            aux = false;
        }
    }//GEN-LAST:event_jButtonActualizarTratamientoActionPerformed

    private void jButtonTratamientoOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTratamientoOnActionPerformed
        if (jTablaTratamientos.getSelectedRow() != -1) {
            int id = 0;
            Integer idTratamiento = (Integer) modeloTabla.getValueAt(jTablaTratamientos.getSelectedRow(), id);
            for (Tratamiento t : tratamientoData.mostrarTratamientos()) {
                if (idTratamiento == t.getIdTratamiento() && t.isActivo() == true) {
                    JOptionPane.showMessageDialog(this, "El tratamiento se encuentra activo.");
                    return;
                } else if (idTratamiento == t.getIdTratamiento() && t.isActivo() == false) {
                    tratamientoData.altaLogica(idTratamiento);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una fila antes de continuar.");
        }
        rows();
    }//GEN-LAST:event_jButtonTratamientoOnActionPerformed

    private void jButtonTratamientoOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTratamientoOffActionPerformed
        if (jTablaTratamientos.getSelectedRow() != -1) {
            int id = 0;
            Integer idTratamiento = (Integer) modeloTabla.getValueAt(jTablaTratamientos.getSelectedRow(), id);
            for (Tratamiento t : tratamientoData.mostrarTratamientos()) {
                if (idTratamiento == t.getIdTratamiento() && t.isActivo() == false) {
                    JOptionPane.showMessageDialog(this, "El tratamiento se encuentra inactivo.");
                    return;
                } else if (idTratamiento == t.getIdTratamiento() && t.isActivo() == true) {
                    tratamientoData.bajaLogica(idTratamiento);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una fila antes de continuar.");
        }
        rows();
    }//GEN-LAST:event_jButtonTratamientoOffActionPerformed

    private void jButtonBorrarTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarTratamientoActionPerformed
        if (jTablaTratamientos.getSelectedRow() != -1) {
            int id = 0;
            Integer idTratamiento = (Integer) modeloTabla.getValueAt(jTablaTratamientos.getSelectedRow(), id);
            int confirm = JOptionPane.showConfirmDialog(this, "¿Esta seguro de que desea borrar el tratamiento \nde la base de datos?", "Warning", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            switch (confirm) {
                case JOptionPane.NO_OPTION:
                    return;
                case JOptionPane.YES_OPTION:
                    tratamientoData.borrarTratamiento(idTratamiento);
                    break;
                default:
                    return;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una fila antes de continuar.");
        }
        rows();
    }//GEN-LAST:event_jButtonBorrarTratamientoActionPerformed

    private void jRadioButtonTodosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonTodosMouseClicked
        rows();
    }//GEN-LAST:event_jRadioButtonTodosMouseClicked

    private void jRadioButtonFacialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonFacialMouseClicked
        rows();
    }//GEN-LAST:event_jRadioButtonFacialMouseClicked

    private void jRadioButtonCorporalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonCorporalMouseClicked
        rows();
    }//GEN-LAST:event_jRadioButtonCorporalMouseClicked

    private void jRadioButtonRelajacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonRelajacionMouseClicked
        rows();
    }//GEN-LAST:event_jRadioButtonRelajacionMouseClicked

    private void jRadioButtonEsteticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonEsteticoMouseClicked
        rows();
    }//GEN-LAST:event_jRadioButtonEsteticoMouseClicked

    private void jButtonActualizarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarListaActionPerformed
        rows();
    }//GEN-LAST:event_jButtonActualizarListaActionPerformed

    private void deshabilitarCampos() {
        jComboBoxIds.setEnabled(false);
        jTextFieldNombre.setEnabled(false);
        jTextFieldDetalle.setEnabled(false);
        jTextFieldProductos.setEnabled(false);
        jTextFieldDuracion.setEnabled(false);
        jTextFieldCosto.setEnabled(false);
    }
    
    private void habilitarCampos() {
        jComboBoxIds.setEnabled(true);
        jTextFieldNombre.setEnabled(true);
        jTextFieldDetalle.setEnabled(true);
        jTextFieldProductos.setEnabled(true);
        jTextFieldDuracion.setEnabled(true);
        jTextFieldCosto.setEnabled(true);
    }
    
    private void limpiarCampos() {
        jTextFieldNombre.setText(null);
        jTextFieldDetalle.setText(null);
        jTextFieldProductos.setText(null);
        jTextFieldDuracion.setText(null);
        jTextFieldCosto.setText(null);
    }
    
    private void habilitarBotones() {
        jButtonCargarTratamiento.setEnabled(true);
        jButtonActualizarTratamiento.setEnabled(true);
        jButtonBorrarTratamiento.setEnabled(true);
        jButtonTratamientoOn.setEnabled(true);
        jButtonTratamientoOff.setEnabled(true);
    }
    
    private void deshabilitarBotones() {
        jButtonCargarTratamiento.setEnabled(false);
        jButtonActualizarTratamiento.setEnabled(false);
        jButtonBorrarTratamiento.setEnabled(false);
        jButtonTratamientoOn.setEnabled(false);
        jButtonTratamientoOff.setEnabled(false);
    }
    
    private void cargarId() {
        for (Tratamiento tratamiento : tratamientoData.mostrarTratamientos()) {
            jComboBoxIds.addItem(tratamiento.getIdTratamiento());
        }
    }
    
    private void columns() {
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("Tipo");
        modeloTabla.addColumn("Detalle");
        modeloTabla.addColumn("Productos");
        modeloTabla.addColumn("Duracion");
        modeloTabla.addColumn("Costo");
        modeloTabla.addColumn("Activo");
        jTablaTratamientos.setModel(modeloTabla);
    }
    
    private void rows() {
        modeloTabla.setRowCount(0);
        List<Tratamiento> listaTratamientos = new ArrayList<>(tratamientoData.mostrarTratamientos());
        for (Tratamiento trats : listaTratamientos) {
            boolean aux = false;
            if (jRadioButtonTodos.isSelected()) {
                aux = true;
            } else if (jRadioButtonRelajacion.isSelected() && trats.getNombre().equalsIgnoreCase("relajación")) {
                aux = true;
            } else if (jRadioButtonFacial.isSelected() && trats.getNombre().equalsIgnoreCase("facial")) {
                aux = true;
            } else if (jRadioButtonEstetico.isSelected() && trats.getNombre().equalsIgnoreCase("estético")) {
                aux = true;
            } else if (jRadioButtonCorporal.isSelected() && trats.getNombre().equalsIgnoreCase("corporal")) {
                aux = true;
            }
            if (aux) {
                Object[] filas = {
                    trats.getIdTratamiento(), trats.getNombre(), trats.getDetalle(), trats.getProductosT(), trats.getDuracion(), trats.getCosto(), (trats.isActivo() ? "Activo" : "Inactivo")
                };
                modeloTabla.addRow(filas);
            }
        }
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonActualizarLista;
    private javax.swing.JButton jButtonActualizarTratamiento;
    private javax.swing.JButton jButtonBorrarTratamiento;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCargarTratamiento;
    private javax.swing.JButton jButtonTratamientoOff;
    private javax.swing.JButton jButtonTratamientoOn;
    private javax.swing.JComboBox<Integer> jComboBoxIds;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonCorporal;
    private javax.swing.JRadioButton jRadioButtonEstetico;
    private javax.swing.JRadioButton jRadioButtonFacial;
    private javax.swing.JRadioButton jRadioButtonRelajacion;
    private javax.swing.JRadioButton jRadioButtonTodos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaTratamientos;
    private javax.swing.JTextField jTextFieldCosto;
    private javax.swing.JTextField jTextFieldDetalle;
    private javax.swing.JTextField jTextFieldDuracion;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldProductos;
    // End of variables declaration//GEN-END:variables
}
