/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Instalacion;
import Persistencia.Conexion;
import Persistencia.InstalacionData;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matute
 */
public class jifGestionInstalacion extends javax.swing.JInternalFrame {

    Conexion con = new Conexion();
    InstalacionData instdat = new InstalacionData(con);
    private final DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    public jifGestionInstalacion() {
        initComponents();
        columnas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextDetalles = new javax.swing.JTextField();
        jTextPrecio = new javax.swing.JTextField();
        jBotonNuevo = new javax.swing.JButton();
        jBotonGuardar = new javax.swing.JButton();
        jBotonActualizar = new javax.swing.JButton();
        jBotonAlta = new javax.swing.JButton();
        jBotonBaja = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jBotonCerrar = new javax.swing.JButton();
        jBotonActualizarTabla = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setText("Gestion Instalaciones");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        jLabel3.setText("Detalles de uso:");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        jLabel4.setText("Precio/H:");

        jTextNombre.setEnabled(false);
        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });

        jTextDetalles.setEnabled(false);

        jTextPrecio.setEnabled(false);

        jBotonNuevo.setText("Nueva");
        jBotonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonNuevoActionPerformed(evt);
            }
        });

        jBotonGuardar.setText("Guardar");
        jBotonGuardar.setEnabled(false);
        jBotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonGuardarActionPerformed(evt);
            }
        });

        jBotonActualizar.setText("Actualizar");
        jBotonActualizar.setEnabled(false);
        jBotonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonActualizarActionPerformed(evt);
            }
        });

        jBotonAlta.setText("Alta Logica");
        jBotonAlta.setEnabled(false);
        jBotonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonAltaActionPerformed(evt);
            }
        });

        jBotonBaja.setText("Baja Logica");
        jBotonBaja.setEnabled(false);
        jBotonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonBajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(89, 89, 89)
                                .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(99, 99, 99)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBotonGuardar)
                            .addComponent(jBotonActualizar)
                            .addComponent(jBotonNuevo))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBotonAlta)
                            .addComponent(jBotonBaja))))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBotonNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(jBotonGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(jBotonActualizar)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)))
                .addComponent(jBotonAlta)
                .addGap(18, 18, 18)
                .addComponent(jBotonBaja)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        jBotonCerrar.setText("Cerrar");
        jBotonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonCerrarActionPerformed(evt);
            }
        });

        jBotonActualizarTabla.setText("Actualizar Tabla");
        jBotonActualizarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonActualizarTablaActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jBotonCerrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jBotonActualizarTabla, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(196, 196, 196))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jBotonActualizarTabla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBotonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotonCerrar)
                    .addComponent(jBotonActualizarTabla))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDesktopPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreActionPerformed

    private void jBotonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonNuevoActionPerformed
        jTextNombre.setEnabled(true);
        jTextDetalles.setEnabled(true);
        jTextPrecio.setEnabled(true);
        jBotonGuardar.setEnabled(true);
        jBotonNuevo.setEnabled(false);
    }//GEN-LAST:event_jBotonNuevoActionPerformed

    private void jBotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonGuardarActionPerformed
        String regex = "^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$";

        if (!jTextNombre.getText().matches(regex) || jTextNombre.getText().isEmpty() || jTextNombre.getText().length() >= 20) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese un nombre valido.");
            return;
        }
        String nombre = jTextNombre.getText();
        if (jTextDetalles.getText().length() > 50 || jTextDetalles.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese detalles validos.");
            return;
        }
        String detalles = jTextDetalles.getText();
        try {
            double precioh = Double.parseDouble(jTextPrecio.getText());
            Instalacion instalacion = new Instalacion(nombre, detalles, precioh, false);
            instdat.insertarInstalacion(instalacion);
            JOptionPane.showMessageDialog(null, "Se ha Guardado Correctamente la Instalacion");
            jTextNombre.setText("");
            jTextDetalles.setText("");
            jTextPrecio.setText("");
            jBotonGuardar.setEnabled(false);
            jBotonNuevo.setEnabled(true);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por Favor Ingrese un precio valido.");
        }

    }//GEN-LAST:event_jBotonGuardarActionPerformed

    private void columnas() {
        modelo.addColumn("ID instalacion");
        modelo.addColumn("Nombre Instalacion");
        modelo.addColumn("Detalles");
        modelo.addColumn("Precio por Hora");
        modelo.addColumn("Estado");
        jTable.setModel(modelo);
    }


    private void jBotonActualizarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonActualizarTablaActionPerformed

        modelo.setRowCount(0);
        ArrayList<Instalacion> lista = instdat.obtenerInstalaciones();
        if(lista.isEmpty()){
            return;
        }
        for(Instalacion aux: lista){
            Object[] filas = {
                aux.getIdInstalacion(),
                aux.getNombre(),
                aux.getDetalleUso(),
                aux.getPrecioPorHora(),
                aux.isEstado()
            };
            modelo.addRow(filas);
        }
        if(modelo.getRowCount() >0){
            jBotonActualizar.setEnabled(true);
            jBotonAlta.setEnabled(true);
            jBotonBaja.setEnabled(true);
            jBotonGuardar.setEnabled(false);
            jBotonNuevo.setEnabled(false);
            jTextNombre.setEnabled(true);
            jTextDetalles.setEnabled(true);
            jTextPrecio.setEnabled(true);
        }
        
    }//GEN-LAST:event_jBotonActualizarTablaActionPerformed

    private void jBotonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBotonCerrarActionPerformed

    private void jBotonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonActualizarActionPerformed
        jBotonNuevo.setEnabled(false);
        jBotonGuardar.setEnabled(false);
        String regex = "^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$";

        if (!jTextNombre.getText().matches(regex) || jTextNombre.getText().isEmpty() || jTextNombre.getText().length() >= 20) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese un nombre valido.");
            return;
        }
        String nombre = jTextNombre.getText();
        if (jTextDetalles.getText().length() > 50 || jTextDetalles.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese detalles validos.");
            return;
        }
       
        String detalles = jTextDetalles.getText();
        int id=0;
        int filaSeleccionada = jTable.getSelectedRow();
        if(filaSeleccionada != -1){
           id = (int) jTable.getValueAt(filaSeleccionada, 0);
          
        }
        try {
            double precioh = Double.parseDouble(jTextPrecio.getText());
            instdat.actualizarInstalacion(id, nombre, detalles, precioh);
            JOptionPane.showMessageDialog(null, "Se ha actualizado Correctamente la Instalacion");
            jTextNombre.setText("");
            jTextDetalles.setText("");
            jTextPrecio.setText("");
            jBotonGuardar.setEnabled(false);
            jBotonNuevo.setEnabled(true);
            jBotonActualizar.setEnabled(false);
            modelo.setRowCount(0);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por Favor Ingrese un precio valido.");
        }
        
    }//GEN-LAST:event_jBotonActualizarActionPerformed

    private void jBotonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonAltaActionPerformed
        
        int filaSeleccionada = jTable.getSelectedRow();
        if(filaSeleccionada != -1){
           int id = (int) jTable.getValueAt(filaSeleccionada, 0);
           instdat.altaInstalacion(id);
           JOptionPane.showMessageDialog(null,"Se ha dado la alta correctamente a la instalacion seleccionada.");
           modelo.setRowCount(0);
           jBotonAlta.setEnabled(false);
           jBotonBaja.setEnabled(false);
           jBotonActualizar.setEnabled(false);
        }
    }//GEN-LAST:event_jBotonAltaActionPerformed

    private void jBotonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonBajaActionPerformed
         
        int filaSeleccionada = jTable.getSelectedRow();
        if(filaSeleccionada != -1){
           int id = (int) jTable.getValueAt(filaSeleccionada, 0);
           instdat.bajaInstalacion(id);
           JOptionPane.showMessageDialog(null,"Se ha dado la baja correctamente a la instalacion seleccionada.");
           modelo.setRowCount(0);
           jBotonAlta.setEnabled(false);
           jBotonBaja.setEnabled(false);
           jBotonActualizar.setEnabled(false);
        }
    }//GEN-LAST:event_jBotonBajaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotonActualizar;
    private javax.swing.JButton jBotonActualizarTabla;
    private javax.swing.JButton jBotonAlta;
    private javax.swing.JButton jBotonBaja;
    private javax.swing.JButton jBotonCerrar;
    private javax.swing.JButton jBotonGuardar;
    private javax.swing.JButton jBotonNuevo;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextDetalles;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextPrecio;
    // End of variables declaration//GEN-END:variables
}
