package Vista;

import Modelo.Consultorio;
import Persistencia.ConsultorioData;
import static Vista.jfSpaRelax.listaConsultorios;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class jifGestionConsultorios extends javax.swing.JInternalFrame {

    ConsultorioData cd;
    private String aptoOperacion = "ninguno";
    private int idConsultorioSeleccionado = -1;
    private boolean tablaVisible = false;
    private boolean aptoLogicoCambiado = false;

    private final DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }

    };

    public jifGestionConsultorios() {
        initComponents();
        this.cd = new ConsultorioData();
        armarCabecera();
        jTable1.setModel(modelo);
        cargarTabla();

        jtfUsos.setEnabled(false);
        jtfEquipo.setEnabled(false);
        jtfApto.setEnabled(false);

    }

    private void cargarTabla() {
        try {
            listaConsultorios = cd.obtenerConsultorio();
            modelo.setRowCount(0);
            if (listaConsultorios != null && !listaConsultorios.isEmpty()) {
                for (Consultorio c : listaConsultorios) {
                    Object[] fila = {
                        c.getNroConsultorio(),
                        c.getUsos(),
                        c.getEquipamiento(),
                        c.isApto()
                    };
                    modelo.addRow(fila);
                }
            } else {
                System.out.println("No se encontraron consultorios para mostrar");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los consultorios: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    private Consultorio buscarConsultorioPorCodigo(int codigoConsultorio) {
        listaConsultorios = cd.obtenerConsultorio();

        for (Consultorio c : listaConsultorios) {
            if (c.getNroConsultorio() == codigoConsultorio) {
                return c;
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jtfUsos = new javax.swing.JTextField();
        jtfEquipo = new javax.swing.JTextField();
        jtfApto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnAlta = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnMostrar = new javax.swing.JButton();

        btnCerrar.setText("Cerrar");

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Nimbus Sans", 1, 30)); // NOI18N
        jLabel1.setText("Gestión de Consultorios");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingreso de datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel3.setText("Usos:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel4.setText("Equipamento:");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel5.setText("Apto:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfUsos, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfApto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfUsos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfApto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnNuevo.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBorrar.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnAlta.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        btnAlta.setText("Alta");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        btnBaja.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        btnBaja.setText("Baja");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Usos", "Equipamento", "Apto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnMostrar.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        btnMostrar.setText("Mostrar Consultorios");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(btnMostrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlta)
                    .addComponent(btnBaja)
                    .addComponent(btnBorrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrar)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        aptoOperacion = "Nuevo";
        jtfUsos.setText("");
        jtfEquipo.setText("");
        jtfApto.setText("false");
        jtfUsos.setEnabled(true);
        jtfEquipo.setEnabled(true);
        jtfApto.setEnabled(true);

        btnNuevo.setEnabled(false);
        btnAlta.setEnabled(true);
        btnBaja.setEnabled(true);
        btnGuardar.setEnabled(true);

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        if (tablaVisible == false) {
            cargarTabla();
            tablaVisible = true;
            btnMostrar.setText("Ocultar Consultorios");
        } else {
            modelo.setRowCount(0);
            btnMostrar.setText("Mostrar Consultorios");
            tablaVisible = false;
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        aptoOperacion = "Actualizar";

        int filaSeleccionada = jTable1.getSelectedRow();

        if (filaSeleccionada != -1) {
            Object valorId = jTable1.getValueAt(filaSeleccionada, 0);

            int codigoCons = Integer.parseInt(valorId.toString());
            this.idConsultorioSeleccionado = codigoCons;
            Consultorio consultorioSeleccionado = buscarConsultorioPorCodigo(codigoCons);

            if (consultorioSeleccionado != null) {
                jtfUsos.setText(consultorioSeleccionado.getUsos());
                jtfEquipo.setText(consultorioSeleccionado.getEquipamiento());
                jtfApto.setText(String.valueOf(consultorioSeleccionado.isApto()));

                jtfUsos.setEnabled(true);
                jtfEquipo.setEnabled(true);

                btnNuevo.setEnabled(false);
                btnGuardar.setEnabled(true);
                btnBorrar.setEnabled(false);
                btnActualizar.setEnabled(false);
                btnAlta.setEnabled(true);
                btnBaja.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada != -1) {
            btnNuevo.setEnabled(false);
            btnBorrar.setEnabled(true);
            btnActualizar.setEnabled(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada != -1) {
            int id = (int) jTable1.getValueAt(filaSeleccionada, 0);
            cd.altaConsultorio(id);
            JOptionPane.showMessageDialog(null, "Se ha dado la alta correctamente a la instalacion seleccionada.");
            btnActualizar.setEnabled(false);
        } else if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila porfavor.");
        }
        if ("false".equals(jtfApto.getText())) {
            jtfApto.setText("true");
        } else {
            JOptionPane.showMessageDialog(this, "El Estado ya es true, para cambiarlo a false usar el boton 'Baja'",
                     "Error de Logica", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada != -1) {
            int id = (int) jTable1.getValueAt(filaSeleccionada, 0);
            cd.bajaConsultorio(id);
            JOptionPane.showMessageDialog(null, "Se ha dado la baja correctamente a la instalacion seleccionada.");
            btnActualizar.setEnabled(false);
        } else if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila porfavor.");
        }
        if ("true".equals(jtfApto.getText())) {
            jtfApto.setText("false");
        } else {
            JOptionPane.showMessageDialog(this, "El Estado ya es false, para cambiarlo a true usar el boton 'Alta'",
                     "Error de Logica", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBajaActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        btnNuevo.setEnabled(false);
        btnActualizar.setEnabled(false);

        int filaSeleccionada = jTable1.getSelectedRow();

        if (filaSeleccionada != -1) {
            Object valorId = jTable1.getValueAt(filaSeleccionada, 0);

            if (valorId == null) {
                JOptionPane.showMessageDialog(this, "No se puede eliminar: el ID del consultorio es null",
                        "Error de datos", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int opcion = JOptionPane.showConfirmDialog(this, "Estas seguro de que queres borrar los datos del consultorio?",
                    "Confirmar Borrado", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                try {
                    int codigoCons = Integer.parseInt(valorId.toString());
                    Consultorio consultorioSeleccionado = buscarConsultorioPorCodigo(codigoCons);

                    if (consultorioSeleccionado != null) {
                        cd.borrarConsultorio(consultorioSeleccionado.getNroConsultorio());
                        JOptionPane.showMessageDialog(this, "Consultorio borrado con exito.");

                        cargarTabla();
                        jtfUsos.setText("");
                        jtfEquipo.setText("");
                        jtfApto.setText("");
                    } else {
                        JOptionPane.showMessageDialog(this, "No se encontro el consultorio", "Error de Busqueda",
                                JOptionPane.ERROR_MESSAGE);
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Error: El ID del consultorio no es válido",
                            "Error de formato", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un consultorio de la tabla para eliminar",
                    "Selección requerida", JOptionPane.WARNING_MESSAGE);
        }

        btnNuevo.setEnabled(true);
        btnActualizar.setEnabled(true);
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String regexLetras = "^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$";
    String regexNumeros = "\\d+";
    boolean consultorioExiste = false;

    if (  jtfEquipo.getText().isEmpty() || jtfApto.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Todos los campos deben estar completos.", 
            "Error, Campos Vacíos", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!jtfUsos.getText().matches(regexLetras) || !jtfEquipo.getText().matches(regexLetras)) {
        JOptionPane.showMessageDialog(this, 
            "Los campos 'Usos' y 'Equipamiento' solo deben contener letras y espacios.", 
            "Error de Formato", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!jtfApto.getText().equalsIgnoreCase("true") && !jtfApto.getText().equalsIgnoreCase("false")) {
        JOptionPane.showMessageDialog(this, 
            "El campo 'Apto' solo debe ser 'true' o 'false'.", 
            "Error de Formato", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    listaConsultorios = cd.obtenerConsultorio();
    boolean aptoValor = Boolean.parseBoolean(jtfApto.getText());

    if (aptoOperacion.equalsIgnoreCase("Nuevo")) {
        for (Consultorio consultorio : listaConsultorios) {
            if (consultorio.getNroConsultorio() == consultorio.getNroConsultorio()) {
                consultorioExiste = true;
                break;
            }
        }

        if (consultorioExiste) {
            JOptionPane.showMessageDialog(this, 
                "Ya existe un consultorio con el ID ingresado", 
                "Error. Consultorio existente", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        Consultorio nuevoConsultorio = new Consultorio (jtfUsos.getText(), jtfEquipo.getText());
        nuevoConsultorio.setApto(aptoValor);

        cd.insertarConsultorio(nuevoConsultorio);
        JOptionPane.showMessageDialog(this, "Consultorio agregado exitosamente.");

        aptoOperacion = "Ninguno";

    } else if (aptoOperacion.equalsIgnoreCase("Actualizar")) {
        int codConsultorioActualizar = this.idConsultorioSeleccionado;
        Consultorio consultorioActualizar = buscarConsultorioPorCodigo(codConsultorioActualizar);

        if (consultorioActualizar != null) {
            cd.actualizarConsultorio(codConsultorioActualizar, jtfUsos.getText(), jtfEquipo.getText(), aptoValor);
            JOptionPane.showMessageDialog(this, "Consultorio actualizado exitosamente.");
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró el consultorio.", 
                "Error de Búsqueda", JOptionPane.ERROR_MESSAGE);
        }
        aptoOperacion = "Ninguno";
    }

    cargarTabla();
    jtfUsos.setText("");
    jtfEquipo.setText("");
    jtfApto.setText("");

    btnGuardar.setEnabled(false);
    btnNuevo.setEnabled(true);

    jtfUsos.setEnabled(false);
    jtfEquipo.setEnabled(false);
    jtfApto.setEnabled(false);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void armarCabecera() {
        modelo.addColumn("ID");
        modelo.addColumn("Usos");
        modelo.addColumn("Equipamento");
        modelo.addColumn("Apto");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtfApto;
    private javax.swing.JTextField jtfEquipo;
    private javax.swing.JTextField jtfUsos;
    // End of variables declaration//GEN-END:variables
}
